from tkinter import CENTER, DISABLED, FLAT, NORMAL, W


class Styles:
    PRIMARY_COLOR = "#250001"
    WHITE_COLOR = "#FFFFFF"
    BLACK_COLOR = "#000000"
    WHITE_SMOKE_COLOR = "#F3F3F3"

    FONT_ARIAL = "Arial"
    FONT_ARIAL_10 = f"{FONT_ARIAL} 10"
    FONT_ARIAL_12 = f"{FONT_ARIAL} 12"
    FONT_ARIAL_13 = f"{FONT_ARIAL} 13"
    FONT_ARIAL_14 = f"{FONT_ARIAL} 14"
    FONT_ARIAL_15 = f"{FONT_ARIAL} 15"
    FONT_ARIAL_20 = f"{FONT_ARIAL} 20"

    FONT_ARIAL_BOLD_10 = f"{FONT_ARIAL} 10 bold"
    FONT_ARIAL_BOLD_12 = f"{FONT_ARIAL} 12 bold"
    FONT_ARIAL_BOLD_13 = f"{FONT_ARIAL} 13 bold"
    FONT_ARIAL_BOLD_14 = f"{FONT_ARIAL} 14 bold"
    FONT_ARIAL_BOLD_15 = f"{FONT_ARIAL} 15 bold"
    FONT_ARIAL_BOLD_20 = f"{FONT_ARIAL} 20 bold"

    CENTER = CENTER

    ANCHOR_CENTER = CENTER

    RELIEF_FLAT = FLAT

    STATE_NORMAL = NORMAL
    STATE_DISABLED = DISABLED

    CURSOR_HAND2 = "HAND2"

    ANCHOR_W = W
